tasks:
  - init: yarn install
    command: yarn start --sockPort 443

ports:
  - port: 7936

github:
  # https://www.gitpod.io/docs/prebuilds/#configure-prebuilds
  prebuilds:
    pullRequestsFromForks: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - flowtype.flow-for-vscode@1.5.0:AwOT6wgHTF43loZQCAUMLA==
