// This file was generated by src/symbols.ts. DO NOT EDIT.
// @generated

// prettier-ignore
export default {
    "math": {
        "binary": {
            "+": {
                "text": "+",
                "font": "Main-Regular",
                "replace": "+"
            },
            "-": {
                "text": "-",
                "font": "Main-Regular",
                "replace": "-"
            },
            "\": {
                "text": "\\backslash",
                "font": "Main-Regular"
            },
            "*": {
                "text": "\u2217",
                "font": "Main-Regular",
                "replace": "\u2217"
            },
            ".": {
                "text": "\u22C5",
                "font": "Main-Regular",
                "replace": "\u22C5"
            },
            ",": {
                "text": ",",
                "font": "Main-Regular"
            },
            "<": {
                "text": "<",
                "font": "Main-Regular",
                "replace": "<"
            },
            "/": {
                "text": "/",
                "font": "Main-Regular",
                "replace": "/"
            },
            ">": {
                "text": ">",
                "font": "Main-Regular",
                "replace": ">"
            },
            "=": {
                "text": "=",
                "font": "Main-Regular",
                "replace": "="
            },
            ")": {
                "text": ")",
                "font": "Main-Regular"
            },
            "[": {
                "text": "[",
                "font": "Main-Regular"
            },
            "]": {
                "text": "]",
                "font": "Main-Regular"
            },
            "|": {
                "text": "|",
                "font": "Main-Regular"
            },
            "(": {
                "text": "(",
                "font": "Main-Regular"
            },
            "\u2061": {
                "text": "\u2061",
                "font": "Main-Regular"
            },
            "\u2062": {
                "text": "\u2062",
                "font": "Main-Regular"
            },
            "\u2063": {
                "text": "\u2063",
                "font": "Main-Regular"
            },
            "\u2064": {
                "text": "\u2064",
                "font": "Main-Regular"
            },
            "\u22A5": {
                "text": "\u27C2",
                "font": "Main-Regular"
            }
        }
    },
    "text": {}
};
