name: Screenshotter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshotter:
    strategy:
      matrix:
        browser: [chrome, firefox, safari]
        include:
          - browser: chrome
            image: selenium/standalone-chromium:145.0-20260222
          - browser: firefox
            image: selenium/standalone-firefox:128.0-20260222
          - browser: safari
            image: ghcr.io/katex/katex-webkit:1.2
      fail-fast: false
    runs-on: ubuntu-latest
    services:
      selenium:
        image: ${{ matrix.image }}
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run screenshotter
        run: |
          TOKEN="$(cat /proc/sys/kernel/random/uuid | sha256sum | head -c 64)"
          echo "::add-mask::$TOKEN"
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "::stop-commands::$TOKEN"
          SELENIUM_IP=$(docker inspect ${{ job.services.selenium.id }} --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
          
          if [ "${{ matrix.browser }}" = "safari" ]; then
            SELENIUM_ARGS="--selenium-url http://$SELENIUM_IP:4444 --selenium-ip $SELENIUM_IP"
          else
            SELENIUM_ARGS="--selenium-ip selenium"
          fi

          # run in Docker container
          # mount .git readonly to prevent modification
          docker run --rm \
            --network ${{ job.services.selenium.network }} \
            -v "$PWD:/code" \
            -v "$PWD/.git:/code/.git:ro" \
            -w /code \
            -e CI=true \
            node:24 \
            /bin/bash -c "corepack enable && node dockers/screenshotter/screenshotter.js -b ${{ matrix.browser }} --verify --diff --new --katex-ip \$HOSTNAME $SELENIUM_ARGS"
          echo "::$TOKEN::"
        timeout-minutes: 12

      - name: Print Selenium Docker logs
        if: always()
        run: |
          echo "::stop-commands::$TOKEN"
          docker logs ${{ job.services.selenium.id }}
          echo "::$TOKEN::"

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: new-${{ matrix.browser }}
          path: test/screenshotter/new
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: diff-${{ matrix.browser }}
          path: test/screenshotter/diff
